### Recuperar todas las reviews
GET http://localhost:3000/reviews

### Recuperar una review
GET http://localhost:3000/reviews/6529dd140afe47eb19765df3

### Crear una review
POST http://localhost:3000/reviews
Content-Type: application/json

{
  "date": "2023-10-28",
  "dislikes": 0,
  "duration": "132",
  "genre": ["Drama", "Acción"],
  "likes": 0,
  "poster": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAA",
  "rate": "3.2",
  "title": "hola",
  "director": "Francis Ford Coppola"
}

### Actualizar una review
PATCH http://localhost:3000/reviews/6529b0544ee5f51e4e1624e4
Content-Type: application/json

{
    "title": "The Godfather",
    "rate": 1,
    "duration": 175,
    "genres": [
        "Drama",
        "Crimen"
    ],
    "poster": "https://www.imdb.com/title/tt0068646/mediaviewer/rm1469564160/",
    "date": "1972-03-24",
    "genre": [
        "Drama",
        "Acción"
    ],
    "likes": 0,
    "dislikes": 0
}

### Eliminar una review
DELETE http://localhost:3000/reviews/6529b1254ee5f51e4e1624e6